Repository etcd-io/protodoc, pull requests merged in 2025-03, with the labels that each got.

#14 Introduce a go.mod
  go.mod
  go.sum
  main.go
Labels: size/S, approved

#15 Migrate from travisci
  .travis.yml
  Makefile
  scripts/test.sh
  test
Labels: size/M, approved

#16 Removing newline characters which were breaking linting
  main.go
  parse/markdown.go
Labels: approved, size/XS

#17 Updates golang toolchain to version 1.23.7
  go.mod
Labels: size/XS
